describe("Cypress", () => {
  it("tests Cypress", () => {
    cy.viewport(1920, 944);
    cy.visit("http://localhost:3000/login");
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("mathworks");
    cy.get("input[type='email']").type("mathworks69@");
    cy.get("input[type='email']").type("mathworks69@gmail.com");
    cy.get("input[type='password']").click();
    cy.get("input[type='password']").type("admin123");
    cy.get("button").click();
    cy.get("div.p-5 > button:nth-of-type(1)").click();
    cy.get("div.h-\\[20vh\\] > button:nth-of-type(1)").click();
    cy.get("div.h-\\[43vh\\] > button:nth-of-type(5)").click();
    cy.get("div.h-\\[43vh\\] > button:nth-of-type(1)").click();
    cy.get("div.gap-10 > div.gap-10 p").click();
    cy.location("href").should("eq", "http://localhost:3000/login");
    cy.get("a:nth-of-type(3)").click();
    cy.get("div.w-full button").click();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("vshon447@");
    cy.get("input[type='email']").type("vshon447@gmail.com");
    cy.get("input[type='password']").click();
    cy.get("input[type='password']").type("vishnu");
    cy.get("button").click();
    cy.get("div > a:nth-of-type(2)").click();
    cy.get("#__next > div a:nth-of-type(3)").click();
    cy.get("div > a:nth-of-type(1)").click();
    cy.get("div:nth-of-type(1) > div.h-\\[60\\%\\] > a").click();
    cy.get("button.text-\\[indigo\\]").click();
    cy.get("button.text-main").click();
    cy.get("main a").click();
    cy.location("href").should("eq", "http://localhost:3000/candidates");
    cy.get("div.w-\\[45\\%\\] > div > input").click();
    cy.get("div.w-\\[45\\%\\] > div > input").type("good");
    cy.get("textarea").click();
    cy.get("textarea").type("good");
    cy.get("main main").click();
    cy.get("#custom-checkbox-0").click();
    cy.get("#custom-checkbox-2").click();
    cy.get("#custom-checkbox-3").click();
    cy.get("div.gap-10 > main button:nth-of-type(1)").click();
    cy.get("button.mx-5").click();
    cy.get("#__next > div button").click();
    cy.get("input[type='email']").click();
    cy.get("input[type='email']").type("mathworks69@gmail.com");
    cy.get("input[type='password']").click();
    cy.get("input[type='password']").type("admin123");
    cy.get("button").click();
    cy.get("div > a:nth-of-type(2)").click();
    cy.get("a:nth-of-type(3) p").click();
    cy.get("button.bg-main").click();
    cy.get("a:nth-of-type(2) p").click();
    cy.get("button.bg-\\[red\\]").click();
    cy.get("a:nth-of-type(1) > img").click();
    cy.get("div.w-full button").click();
  });
});
