const candidates = [
    {
      "name": "Vishnu Shon",
      "college": "University A",
      "degree": "Computer Science",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword1",
      "telegramId": "836114955",
      "cgpa": "3.9",
      "track": "development",
      "skillset": ["development", "design"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Bob Smith",
      "college": "College B",
      "degree": "Electrical Engineering",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword2",
      "telegramId": "836114955",
      "cgpa": "3.7",
      "track": "product",
      "skillset": ["product", "marketing"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Charlie Brown",
      "college": "University C",
      "degree": "Mechanical Engineering",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword3",
      "telegramId": "836114955",
      "cgpa": "3.5",
      "track": "marketing",
      "skillset": ["marketing", "design"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "David Miller",
      "college": "College D",
      "degree": "Information Technology",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword4",
      "telegramId": "836114955",
      "cgpa": "3.8",
      "track": "development",
      "skillset": ["development", "product"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Eva Wilson",
      "college": "University E",
      "degree": "Computer Science",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword5",
      "telegramId": "836114955",
      "cgpa": "3.6",
      "track": "design",
      "skillset": ["design", "marketing"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Frank Jackson",
      "college": "College F",
      "degree": "Electrical Engineering",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword6",
      "telegramId": "836114955",
      "cgpa": "3.9",
      "track": "product",
      "skillset": ["product", "development"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Grace Martin",
      "college": "University G",
      "degree": "Mechanical Engineering",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword7",
      "telegramId": "836114955",
      "cgpa": "3.7",
      "track": "marketing",
      "skillset": ["marketing", "design"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Harry White",
      "college": "College H",
      "degree": "Information Technology",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword8",
      "telegramId": "836114955",
      "cgpa": "3.5",
      "track": "development",
      "skillset": ["development", "product"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Ivy Johnson",
      "college": "University I",
      "degree": "Computer Science",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword9",
      "telegramId": "836114955",
      "cgpa": "3.8",
      "track": "design",
      "skillset": ["design", "marketing"],
      "status": "TOBEINTERVIEWED"
    },
    {
      "name": "Jack Robinson",
      "college": "College J",
      "degree": "Electrical Engineering",
      "email": "vishnu20414@iiitd.ac.in",
      "admin": "adminPassword10",
      "telegramId": "836114955",
      "cgpa": "3.6",
      "track": "product",
      "skillset": ["product", "development"],
      "status": "TOBEINTERVIEWED"
    }
  ]  